### ISSUE TITLE
Speed/Caching Improvements?

### ISSUE THREAD

**Issue by NathanielHill** [mheap/github-action-required-labels#2]
This action is twice as slow as the previous label checker we were using, but it doesn't generate extra notifications which is why we went with it.

Do you think there's room for speeding it up?

**Comment by mheap** [comment]
I've just released `v1.1.0` and updated the `v1` tag to point to it. It uses https://github.com/mheap/github-action-auto-compile-node to build a JS pack rather than building a docker image on every run.

TL;DR: Execution time for this action is now ~1s, down from 25s

**Comment by NathanielHill** [comment]
@mheap Okay, wow that's a massive speed increase! Thanks for working on that, but I do find updating a version tag rather than tagging a new release a bit puzzling.

**Comment by NathanielHill** [comment]
That does make it easier for me, but hopefully doesn't break for anyone.

**Comment by NathanielHill** [comment]
Oh, I see what you're doing there with `v1` versus `v1.0.0`. Okay, makes more sense. Might want to put that in the main `README.md`

Thanks
