### ISSUE TITLE
Attempts to add comment when default is "false"

### ISSUE THREAD

**Issue by garytimuss** [mheap/github-action-required-labels#39]
`fatal Error: The GITHUB_TOKEN environment variable must be set to add a comment `

We don't have GITHUB_TOKEN env set because we don't want to add a comment 

exitWithError should give the error instead is failing

    description: "Add a comment to the PR if required labels are missing"
    default: "false"
    required: false

Expect the default should be false not "false" for boolean test to fail by default to not add the comment 
caused by https://github.com/mheap/github-action-required-labels/commit/4ae53dd40a63ca66263a72d9d88b2747c3b7c4b7#

**Comment by mheap** [comment]
Thanks for the report! I've just published 2.2.3 that resolves this issue. Sorry for the unintentional break - I'm adding unit tests for this behaviour now
