### ISSUE TITLE
Need to update v2 tag

### ISSUE THREAD

**Issue by e3b0c442** [mheap/github-action-required-labels#41]
Hello,

You pushed a fix for the comment issue as v2.2.3, but the v2 tag is still pointing at v2.2.2, can you update?

Thanks!

**Comment by e3b0c442** [comment]
Looks like there's an extra dot in `v.2.2.3` so Marketplace didn't get the v2 tag updated automatically like it would normally

**Comment by mheap** [comment]
All resolved! That'll teach me for trying to release whilst at an event 😭
