### ISSUE TITLE
`The "set-output" command is deprecated and will be disabled soon` warning

### ISSUE THREAD

**Issue by RusAkh** [mheap/github-action-required-labels#42]
More info [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands)

Every pull request on [Osmosis](https://github.com/osmosis-labs/osmosis) finishes with this warning. Seems like this action is responsible for it. Ex: [example](https://github.com/osmosis-labs/osmosis/actions/runs/3450249803/jobs/5758728072)
From the first link, my guess it is due to not using `@actions/core v1.10.0` but may be something else

**Comment by RusAkh** [comment]
I checked this action and it seems like nowhere here set-output nor save-state are being used, so if you have any ideas why it might happen, I would be really thankful for any info!

**Comment by RusAkh** [comment]
might be due to [this](https://github.com/mheap/github-action-required-labels/blob/main/package-lock.json#L19-L20)

**Comment by mheap** [comment]
I'm using https://github.com/JasonEtco/actions-toolkit for this, which needs to bump its version of `actions/core`. I'm working on a solution and it'll be shipped _way_ before the EOL date for the existing functionality

**Comment by longrunningprocess** [comment]
> I'm using https://github.com/JasonEtco/actions-toolkit for this, which needs to bump its version of `actions/core`. I'm working on a solution and it'll be shipped _way_ before the EOL date for the existing functionality

just checking in on this, did I understand you correctly that you'll fix it rather than asking Jason to update his?  I didn't notice an issue for it over in his repo and I'm not sure it's being worked on anymore.  Thanks!

**Comment by mheap** [comment]
> just checking in on this, did I understand you correctly that you'll fix it rather than asking Jason to update his? 

Yep! I'm slowly converting actions to `@actions/core` and `@actions/github`. This is on my list for the holiday break 👍

**Comment by longrunningprocess** [comment]
😎 , appreciate it man!

**Comment by longrunningprocess** [comment]
just curious, I presume this will still be released under v2, is that what you're thinking?

**Comment by mheap** [comment]
I'm reasonably confident this will be a v2 update. If there are any changes which could be considered breaking (I don't intend to make any, but it all depends on the implementation) it'll go out as v3

**Comment by mheap** [comment]
I released this as v3 as v2 has code to handle the `neutral` exit code which no longer exists. `@actions/core` doesn't support it, and rather than adding custom code to handle something that isn't used, I chose to remove the neutral `exit_type`. This necessitated a major release

**Comment by longrunningprocess** [comment]
make sense, thanks!
