### ISSUE TITLE
Idea: Update existing comment(s)?

### ISSUE THREAD

**Issue by tstackhouse** [mheap/github-action-required-labels#50]
This action is great, though it would be nice if we could update or remove and recreate comments rather than just adding new ones :slightly_smiling_face:

**Comment by mheap** [comment]
This is now released as v4 - we needed a major version bump as it changes the behaviour of adding comments and some people may be relying on getting notifications

**Comment by tstackhouse** [comment]
Sweet!  Thanks for making such a useful action ❤️
