### ISSUE TITLE
Please update Node18 to Node20

### ISSUE THREAD

**Issue by Fameing** [mheap/github-action-required-labels#67]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mheap/github-action-required-labels@v5. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by mheap** [comment]
All done 🙌 

https://github.com/mheap/github-action-required-labels/commit/cc7a79fadbba6ed1d6f0efd70707e7b8bf7e6910#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R4

**Comment by Fameing** [comment]
@mheap Thank you very much. 🥳🥳🥳
